# Generated by Django 5.0 on 2023-12-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_population', models.IntegerField(blank=True, null=True, verbose_name='Minimal amount')),
                ('max_population', models.IntegerField(blank=True, null=True, verbose_name='Maximal amount')),
                ('tank_size_liters', models.IntegerField(verbose_name='Minimal tank size (liters)')),
            ],
        ),
    ]
